### PR TITLE
Event management

### LINKED ISSUE #13: Event management
Add event management for ad loaded, failed, displayed, etc callbacks using streams

for example:

```dart
enum AdEventType {loaded, failedToLoad, etc}
class AdEvent {
    final AdEventType type;
    final String? error;
    final Object? data;
    final AdNetwork;
    final AdUnitType;
}
final _onEventController = StreamController< AdEvent >.broadcast();

/// The events this ad throws. Listen to it using:
///
/// ```dart
/// ad.onEvent.listen((event) {
///   print(event);
/// });
/// ```
Stream< AdEvent > get onEvent => onEventController.stream;

/// to fire an event use:
_onEventController.add(AdEvent);
```

### PR DESCRIPTION
**Pull request by ahmadkhandev**
closes #13

### CODE REVIEW

File: lib/src/easy_ads.dart [hunk 1]
```diff
@@ -28,6 +31,9 @@ class EasyAds {
   EasyAdFailedCallback? onAdFailedToShow;
   EasyAdEarnedReward? onEarnedReward;
```
Comment (nooralibutt) [inline lib/src/easy_ads.dart:32]: need to remove these. dont need them any more
```dart
EasyAdNetworkInitialized? onAdNetworkInitialized;
  EasyAdCallback? onAdLoaded;
  EasyAdCallback? onAdDismissed;
  EasyAdCallback? onAdShowed;
  EasyAdFailedCallback? onAdFailedToLoad;
   EasyAdFailedCallback? onAdFailedToShow;
   EasyAdEarnedReward? onEarnedReward;
```

File: lib/src/easy_ads.dart [hunk 2]
```diff
@@ -1,8 +1,11 @@
+import 'dart:async';
```
Comment (nooralibutt) [inline lib/src/easy_ads.dart:1]: you didn't update the example app for how to use these events, no changelog, no read me update?

**Review by nooralibutt — CHANGES_REQUESTED** [review]

File: lib/src/easy_ads.dart [hunk 3]
```diff
@@ -54,7 +52,19 @@ class EasyAds {
...
+        adNetwork: AdNetwork.admob,
+        adUnitType: AdUnitType.interstitial,
+        data: status,
+      ));
+      _onEventController.add(AdEvent(
+        type: AdEventType.adNetworkInitialized,
+        adNetwork: AdNetwork.admob,
+        adUnitType: AdUnitType.rewarded,
+        data: status,
+      ));
```
Comment (nooralibutt) [inline lib/src/easy_ads.dart:67]: it wasn't meant for this.

**Review by nooralibutt — CHANGES_REQUESTED** [review]

**Review by nooralibutt — DISMISSED** [review]

**Review by nooralibutt — APPROVED** [review]
